### ISSUE TITLE
Configs aren't loading with the 5/22 update

### ISSUE THREAD

**Issue by HairyMilkshakes** [theletterjwithadot/Ultimate-Config-for-L4D2#4]
Not sure why but I didn't change anything except deleting the custom_config.cfg file and updated the launch params to what's in the ultimateconfig.cfg file:

-lv -high +precache_all_survivors 1 -noborder -novid -console -nojoy -noforcemaccel -noforcemparms -noforcemspd +mat_motion_blur_percent_of_screen_max 0 +clientport 27666

**Comment by HairyMilkshakes** [comment]
Just noticed it isn't the configs that aren't loading but you put -noborder in the launch options. The screen brightness doesn't take effect unless you are in full screen mode under display mode in the option. That was what was making me think the configs weren't working.

Can you share the old launch options you had before the recent edits? With the new launch options here with noborder removed I still have to go into options every time and set the display mode to full screen since the game resets it every time i quit:
-lv -high +precache_all_survivors 1 -novid -console -nojoy -noforcemaccel -noforcemparms -noforcemspd +mat_motion_blur_percent_of_screen_max 0 +clientport 27666

Also, console is showing this as an unknown command: 
`Unknown command "mat_motion_blur_percent_of_screen_max"`

**Comment by theletterjwithadot** [comment]
Hi @HairyMilkshakes

I have reverted the commit and updated (removed mat_motion_blur_percent_of_screen_max) the launch parameters.

The old launch parameter did not have -noborder.

You can copy the new launch parameters that I have just updated.
You will also have to update autoexec.cfg file back to the file that I have reverted to.

The reason for switching to noborder was to reduce the amount of time this game hangs when you alt tab and out. This game has support for NVIDIA Freestyle filters, as such my intention was to allow it to be used instead of using the in-game brightness settings.

I will make this optional in the future edit with explanation.

Cheers and thank you!
J.

**Comment by HairyMilkshakes** [comment]
Thanks for the quick fix the reverted commits work well from tests just now. As FYI borderless windows display mode also doesn't support the below two cvars:

```
mat_monitorgamma								1.6		//# Brightest 1.6 - Darkest 2.6
mat_monitorgamma_tv_enabled						1		//# Set to 0 if the game is too bright for you
```

**Comment by theletterjwithadot** [comment]
Hi @HairyMilkshakes 

You are correct. The alternative way is to use GPU filters or ReShade to make the game brighter if we were to use borderless mode.

I will put this as an optional thing for a future update.

The reason for going borderless was to reduce the crashes and hangs that happen due to alt tabbing when map switching or loading into map, or just when randomly L4D2 decides to stop working when alt tabbed one too many times.

Cheers!
J.
